# 1 

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


# 2

In [4]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

# Printing data types of elements in list_
for element in list_:
    print(type(element))

# Printing data types of elements in array_list
for element in array_list:
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# 3

# 4 

In [5]:
import numpy as np

num_array = np.array([[1, 2, 3], [4, 5, 6]])

# (i) Finding the shape of num_array
shape = num_array.shape
print("Shape:", shape)

# (ii) Finding the size of num_array
size = num_array.size
print("Size:", size)


Shape: (2, 3)
Size: 6


# 5 

In [6]:
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# 6 